apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: rishi-dev-ns
spec: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: rishi-app
  name: rishi-app
  namespace: rishi-dev-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rishi-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rishi-app
    spec:
      containers:
      - image: dockerashu/ashumobiwebapp:6
        name: ashumobiwebapp
        ports:
        - containerPort: 80
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ashusvc1
  name: ashusvc1
  namespace: rishi-dev-ns
spec:
  ports:
  - name: 1234-80
    port: 1234
    protocol: TCP
    targetPort: 80
  selector:
    app: ashusvc1
  type: NodePort
status:
  loadBalancer: {}

